// Generated by scripts/generate-license-key.mjs. Do not edit manually.
export const LICENSE_PUBLIC_KEY = {
  kty: "RSA",
  n: "uT9uclwhc4CjLWCsw_IwzN878U_xQt5vDh66U0nptVq05LhJEO0f863sK_-KbT-2e0HsC3OEew3DlEwxpikIVC7be5c86H5fVSl6Px1bVLc5dvJImlb0d9QLOyRvo7R6Se_PQ-rCGjkh6MZyHR1Moum7IFKP8UFYUXXPWSPhcwKkyeMtSqWrSOqP1aBkSQpgxFyj2EG4pLPqyokGHoJQzDTRO3RNR5aSSWFxwm0SmS57BV-SxpVt-eQLltKTyoZtgA8UIO2zX1SE9NLEV7bi2BesIocQhme5Wgl-4bVexwZUO7fzEZBTHhySEPOxoG4dl5FlX2bi-ema7CdV0wuGcQ",
  e: "AQAB",
  alg: "RS256",
  ext: true,
  key_ops: ["verify"],
} as const;

export const LICENSE_PUBLIC_KEY_FINGERPRINT = "692e958ee0716e66c15b9c53e03723b2dba1678a7efeee2b49811e79eb2f4c19";
