import { CalendarCheck, Pause, Play, Plus, RefreshCw, Trash2 } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, View } from 'react-native';

import { Card } from '@/components/ui/card';
import { Amount } from '@/components/ui/amount';
import { AppText } from '@/components/ui/app-text';
import { AppButton } from '@/components/ui/buttons';
import { AppBottomSheet, ConfirmDialog } from '@/components/ui/dialogs';
import { DateField, FormField, MoneyInput, SelectField, SwitchField } from '@/components/ui/forms';
import { ProgressBar, StatusPill } from '@/components/ui/progress';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/state-view';
import { radius, spacing } from '@/constants/theme';
import type { Bill, RecurringTemplate, SinkingFund } from '@/domain/types';
import { useApp } from '@/providers/app-provider';
import { usePreferences } from '@/providers/preferences-provider';
import { formatCurrency, formatDate, formatMonth, parseMoney, today } from '@/utils/format';

export function FundsModule() {
  const { snapshot, mutate, isMutating, isOnline } = useApp();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<SinkingFund | null>(null);
  const [adjusting, setAdjusting] = useState<SinkingFund | null>(null);
  const [name, setName] = useState('');
  const [purpose, setPurpose] = useState('Lainnya');
  const [target, setTarget] = useState('');
  const [current, setCurrent] = useState('');
  const [monthly, setMonthly] = useState('');
  const [targetDate, setTargetDate] = useState(today());
  const [accountId, setAccountId] = useState('');
  const [adjustType, setAdjustType] = useState('allocate');
  const [adjustAmount, setAdjustAmount] = useState('');
  const [adjustNote, setAdjustNote] = useState('');
  const [error, setError] = useState<string | null>(null);
  const funds = snapshot?.sinkingFunds ?? [];
  const eligibleAccounts = snapshot?.accounts.filter((item) => !item.liability && ['Bank', 'E-Wallet', 'Cash', 'Deposit'].includes(item.type)) ?? [];
  const showForm = (fund?: SinkingFund) => { setEditing(fund ?? null); setName(fund?.name ?? ''); setPurpose(fund?.purpose ?? 'Lainnya'); setTarget(fund ? String(fund.targetAmount) : ''); setCurrent(fund ? String(fund.currentAmount) : ''); setMonthly(fund ? String(fund.monthlyContribution) : ''); setTargetDate(fund?.targetDate || today()); setAccountId(fund?.accountId ?? ''); setError(null); setOpen(true); };
  const save = async () => {
    try {
      if (!name.trim() || parseMoney(target) <= 0 || !accountId) throw new Error('Nama, target, dan akun referensi wajib diisi.');
      const payload = { name: name.trim(), purpose, targetAmount: parseMoney(target), currentAmount: parseMoney(current), monthlyContribution: parseMoney(monthly), targetDate, accountId, color: editing?.color ?? '#16876f' };
      await mutate(editing ? 'updateSinkingFund' : 'createSinkingFund', editing ? { ...payload, fundId: editing.id } : payload);
      setOpen(false);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Pos dana gagal disimpan.'); }
  };
  return <View style={{ gap: spacing.md }}>
    <AppButton icon={Plus} fullWidth disabled={!isOnline} onPress={() => showForm()}>Tambah pos dana</AppButton>
    {!funds.length ? <EmptyState title="Belum ada pos dana" message="Alokasikan sebagian saldo untuk kebutuhan tertentu tanpa mengubah saldo akun." /> : funds.map((fund) => <Card key={fund.id} style={{ gap: spacing.sm }}>
      <Pressable accessibilityRole="button" onPress={() => showForm(fund)}><View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }}><View style={{ flex: 1 }}><AppText variant="title">{fund.name}</AppText><AppText variant="caption" muted>{fund.purpose} · {formatDate(fund.targetDate)}</AppText></View><StatusPill label={fund.active ? 'Aktif' : 'Arsip'} tone={fund.active ? 'positive' : 'neutral'} /></View></Pressable>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Amount value={fund.currentAmount} variant="label" /><Amount value={fund.targetAmount} variant="label" /></View><ProgressBar value={fund.targetAmount ? fund.currentAmount / fund.targetAmount * 100 : 0} label={`Alokasi ${fund.name}`} color={fund.color} />
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }}><AppButton tone="secondary" onPress={() => { setAdjusting(fund); setAdjustAmount(''); setAdjustType('allocate'); }}>Atur alokasi</AppButton><AppButton tone="ghost" onPress={() => void mutate('archiveSinkingFund', { fundId: fund.id }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Gagal mengarsipkan.'))}>Arsipkan</AppButton></View>
    </Card>)}
    {error ? <Card style={{ borderColor: '#d65b67' }}><AppText style={{ color: '#d65b67' }}>{error}</AppText></Card> : null}
    <AppBottomSheet visible={open} title={editing ? 'Ubah pos dana' : 'Pos dana baru'} onClose={() => setOpen(false)} footer={<AppButton fullWidth loading={isMutating} onPress={() => void save()}>Simpan</AppButton>}>
      <FormField label="Nama" value={name} onChangeText={setName} maxLength={120} /><SelectField label="Tujuan" value={purpose} onChange={setPurpose} options={['Kendaraan', 'Pajak', 'Liburan', 'Pendidikan', 'Rumah', 'Kesehatan', 'Teknologi', 'Lainnya'].map((value) => ({ label: value, value }))} /><MoneyInput label="Target" value={target} onChangeValue={setTarget} />{!editing ? <MoneyInput label="Alokasi awal" value={current} onChangeValue={setCurrent} /> : null}<MoneyInput label="Kontribusi bulanan" value={monthly} onChangeValue={setMonthly} /><DateField label="Tanggal target" value={targetDate} onChange={setTargetDate} /><SelectField label="Akun referensi" value={accountId} onChange={setAccountId} options={eligibleAccounts.map((item) => ({ label: item.name, value: item.id, description: formatCurrency(item.balance) }))} />
    </AppBottomSheet>
    <AppBottomSheet visible={Boolean(adjusting)} title={`Atur ${adjusting?.name ?? 'alokasi'}`} onClose={() => setAdjusting(null)} footer={<AppButton fullWidth loading={isMutating} onPress={() => { if (!adjusting) return; void mutate('adjustSinkingFund', { fundId: adjusting.id, type: adjustType, amount: parseMoney(adjustAmount), date: today(), note: adjustNote }).then(() => setAdjusting(null)).catch((cause) => setError(cause instanceof Error ? cause.message : 'Alokasi gagal.')); }}>Simpan entry</AppButton>}>
      <AppText muted>Entry alokasi tercatat, tetapi tidak mengubah saldo ledger.</AppText><SelectField label="Jenis" value={adjustType} onChange={setAdjustType} options={[{ label: 'Tambah alokasi', value: 'allocate' }, { label: 'Lepas alokasi', value: 'release' }]} /><MoneyInput label="Nominal" value={adjustAmount} onChangeValue={setAdjustAmount} /><FormField label="Catatan" value={adjustNote} onChangeText={setAdjustNote} maxLength={240} />
    </AppBottomSheet>
  </View>;
}

export function BillsModule() {
  const { snapshot, selectedMonth, mutate, isMutating, isOnline } = useApp();
  const { colors } = usePreferences();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Bill | null>(null);
  const [paying, setPaying] = useState<Bill | null>(null);
  const [deleting, setDeleting] = useState<Bill | null>(null);
  const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('Tagihan'); const [accountId, setAccountId] = useState(''); const [liabilityId, setLiabilityId] = useState(''); const [dueDate, setDueDate] = useState(today()); const [duration, setDuration] = useState(''); const [phased, setPhased] = useState(false); const [phases, setPhases] = useState<Array<{ label: string; durationMonths: number; amount: number }>>([]);
  const [error, setError] = useState<string | null>(null);
  const bills = snapshot?.bills ?? [];
  const showForm = (bill?: Bill) => { setEditing(bill ?? null); setName(bill?.name ?? ''); setAmount(bill ? String(bill.amount) : ''); setCategory(bill?.category ?? 'Tagihan'); setAccountId(bill?.accountId ?? ''); setLiabilityId(bill?.liabilityAccountId ?? ''); setDueDate(bill?.dueDate || today()); setDuration(bill?.durationMonths ? String(bill.durationMonths) : ''); setPhases(bill?.installmentPhases ?? []); setPhased(Boolean(bill?.installmentPhases.length)); setOpen(true); };
  const save = async () => {
    try {
      if (!name.trim() || !accountId || (!phased && parseMoney(amount) <= 0)) throw new Error('Nama, nominal, dan akun pembayaran wajib diisi.');
      if (phased && (phases.length < 2 || phases.some((phase) => !phase.label.trim() || phase.durationMonths <= 0 || phase.amount <= 0))) throw new Error('Skema bertahap memerlukan minimal dua fase valid.');
      const payload = { name: name.trim(), amount: parseMoney(amount), category, accountId, liabilityAccountId: liabilityId, dueDate, frequency: 'monthly', reminderDays: [7, 3, 1, 0], durationMonths: phased ? '' : duration ? Number(duration) : '', installmentPhases: phased ? phases : [] };
      await mutate(editing ? 'updateBill' : 'createBill', editing ? { ...payload, billId: editing.id, paidCount: editing.paidCount } : payload); setOpen(false);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Tagihan gagal disimpan.'); }
  };
  return <View style={{ gap: spacing.md }}>
    <AppButton icon={Plus} fullWidth disabled={!isOnline} onPress={() => showForm()}>Tambah tagihan</AppButton>
    {!bills.length ? <EmptyState title="Belum ada tagihan" message="Tambahkan tagihan bulanan atau cicilan agar jatuh tempo terpantau." /> : bills.map((bill) => <Pressable key={bill.id} accessibilityRole="button" onPress={() => showForm(bill)}>{({ pressed }) => <Card style={{ gap: spacing.sm, opacity: pressed ? 0.75 : 1 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }}><View style={{ flex: 1 }}><AppText variant="title">{bill.name}</AppText><AppText variant="caption" muted>Jatuh tempo {formatDate(bill.dueDate)}{bill.durationMonths ? ` · ${bill.paidCount}/${bill.durationMonths} cicilan` : ''}</AppText></View><StatusPill label={bill.completed ? 'Selesai' : bill.paid ? 'Dibayar' : 'Aktif'} tone={bill.completed || bill.paid ? 'positive' : 'warning'} /></View><Amount value={bill.amount} variant="title" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }}><AppButton tone="secondary" disabled={bill.completed || bill.lastPaidPeriod === selectedMonth} onPress={() => setPaying(bill)}>Bayar</AppButton><AppButton tone="ghost" icon={Trash2} onPress={() => setDeleting(bill)}>Hapus</AppButton></View></Card>}</Pressable>)}
    {error ? <Card style={{ borderColor: colors.negative }}><AppText style={{ color: colors.negative }}>{error}</AppText></Card> : null}
    <AppBottomSheet visible={open} title={editing ? 'Ubah tagihan' : 'Tagihan baru'} onClose={() => setOpen(false)} footer={<AppButton fullWidth loading={isMutating} onPress={() => void save()}>Simpan tagihan</AppButton>}><FormField label="Nama" value={name} onChangeText={setName} maxLength={100} />{!phased ? <MoneyInput label="Nominal per periode" value={amount} onChangeValue={setAmount} /> : null}<SelectField label="Kategori" value={category} onChange={setCategory} options={(snapshot?.categories.filter((item) => item.active && item.type === 'expense').map((item) => ({ label: item.name, value: item.name })) ?? []).concat([{ label: 'Kewajiban', value: 'Kewajiban' }])} /><SelectField label="Akun pembayaran" value={accountId} onChange={setAccountId} options={snapshot?.accounts.filter((item) => !item.liability).map((item) => ({ label: item.name, value: item.id })) ?? []} /><SelectField label="Akun kewajiban" value={liabilityId} onChange={setLiabilityId} options={[{ label: 'Bukan pembayaran kewajiban', value: '' }, ...(snapshot?.accounts.filter((item) => item.liability).map((item) => ({ label: item.name, value: item.id })) ?? [])]} /><DateField label="Jatuh tempo" value={dueDate} onChange={setDueDate} /><SwitchField label="Skema cicilan bertahap" description="Nominal berubah setelah durasi fase selesai." value={phased} onChange={(enabled) => { setPhased(enabled); if (enabled && phases.length < 2) setPhases([{ label: 'Fase 1', durationMonths: 1, amount: parseMoney(amount) }, { label: 'Fase 2', durationMonths: 1, amount: parseMoney(amount) }]); }} />{phased ? <Card style={{ gap: spacing.md }}>{phases.map((phase, index) => <View key={index} style={{ gap: spacing.xs }}><FormField label={`Label fase ${index + 1}`} value={phase.label} onChangeText={(label) => setPhases((value) => value.map((item, itemIndex) => itemIndex === index ? { ...item, label } : item))} /><FormField label="Durasi bulan" value={String(phase.durationMonths)} onChangeText={(raw) => setPhases((value) => value.map((item, itemIndex) => itemIndex === index ? { ...item, durationMonths: Number(raw || 0) } : item))} keyboardType="number-pad" /><MoneyInput label="Nominal fase" value={String(phase.amount)} onChangeValue={(raw) => setPhases((value) => value.map((item, itemIndex) => itemIndex === index ? { ...item, amount: parseMoney(raw) } : item))} />{phases.length > 2 ? <AppButton tone="ghost" onPress={() => setPhases((value) => value.filter((_, itemIndex) => itemIndex !== index))}>Hapus fase</AppButton> : null}</View>)}<AppButton tone="secondary" onPress={() => setPhases((value) => [...value, { label: `Fase ${value.length + 1}`, durationMonths: 1, amount: parseMoney(amount) }])}>Tambah fase</AppButton></Card> : <FormField label="Total tenor (bulan)" value={duration} onChangeText={setDuration} keyboardType="number-pad" inputMode="numeric" placeholder="Kosong untuk tanpa tenor" />}</AppBottomSheet>
    <ConfirmDialog visible={Boolean(paying)} title="Catat pembayaran tagihan?" message={`${paying?.name ?? ''} sebesar ${formatCurrency(paying?.amount ?? 0)} akan dicatat ke ledger untuk ${formatMonth(selectedMonth)}.${paying?.liabilityAccountId ? ' Pembayaran dibuat sebagai transfer ke akun kewajiban.' : ''}`} confirmLabel="Bayar sekarang" loading={isMutating} onCancel={() => setPaying(null)} onConfirm={() => { if (!paying) return; void mutate('markBillPaid', { billId: paying.id, period: selectedMonth, date: today() }).then(() => setPaying(null)).catch((cause) => { setPaying(null); setError(cause instanceof Error ? cause.message : 'Pembayaran gagal.'); }); }} />
    <ConfirmDialog visible={Boolean(deleting)} title="Hapus tagihan?" message="Jadwal tagihan dihapus, tetapi transaksi pembayaran sebelumnya tetap ada di ledger." destructive loading={isMutating} confirmLabel="Hapus" onCancel={() => setDeleting(null)} onConfirm={() => { if (!deleting) return; void mutate('deleteBill', { billId: deleting.id }).then(() => setDeleting(null)).catch((cause) => setError(cause instanceof Error ? cause.message : 'Gagal menghapus.')); }} />
  </View>;
}

export function CalendarModule() {
  const { snapshot, selectedMonth } = useApp();
  const { colors } = usePreferences();
  const events = useMemo(() => [
    ...(snapshot?.bills.map((item) => ({ id: `bill-${item.id}`, date: item.dueDate, title: item.name, kind: 'Tagihan', done: item.paid || item.completed, amount: item.amount })) ?? []),
    ...(snapshot?.recurring.map((item) => ({ id: `rec-${item.id}`, date: item.nextDueDate, title: item.name, kind: item.isSubscription ? 'Langganan' : 'Rutin', done: false, amount: item.amount })) ?? []),
    ...(snapshot?.goals.map((item) => ({ id: `goal-${item.id}`, date: item.deadline, title: item.name, kind: 'Deadline target', done: item.current >= item.target, amount: item.target - item.current })) ?? []),
  ].filter((item) => item.date.startsWith(selectedMonth)).sort((a, b) => a.date.localeCompare(b.date)), [selectedMonth, snapshot?.bills, snapshot?.goals, snapshot?.recurring]);
  return <View style={{ gap: spacing.md }}><Card style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}><CalendarCheck size={24} color={colors.primary} /><View><AppText variant="title">Agenda {formatMonth(selectedMonth)}</AppText><AppText variant="caption" muted>{events.length} agenda terjadwal</AppText></View></Card>{!events.length ? <EmptyState title="Agenda kosong" message="Tagihan, transaksi rutin, dan deadline target bulan ini akan tampil di sini." /> : events.map((event) => <Card key={event.id} style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}><View style={{ width: 48, alignItems: 'center', padding: 6, borderRadius: radius.md, backgroundColor: colors.primarySoft }}><AppText variant="title">{event.date.slice(8, 10)}</AppText><AppText variant="caption">{formatDate(event.date, { month: 'short' })}</AppText></View><View style={{ flex: 1 }}><AppText variant="label">{event.title}</AppText><AppText variant="caption" muted>{event.kind}</AppText></View><View style={{ alignItems: 'flex-end', gap: 4 }}><Amount value={event.amount} variant="label" /><StatusPill label={event.done ? 'Selesai' : event.date < today() ? 'Terlambat' : 'Akan datang'} tone={event.done ? 'positive' : event.date < today() ? 'negative' : 'info'} /></View></Card>)}</View>;
}

export function RecurringModule() {
  const { snapshot, read, mutate, isMutating, isOnline } = useApp();
  const [items, setItems] = useState<RecurringTemplate[]>(snapshot?.recurring ?? []);
  const [loading, setLoading] = useState(!snapshot); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(false); const [confirming, setConfirming] = useState<RecurringTemplate | null>(null);
  const [name, setName] = useState(''); const [type, setType] = useState<'income' | 'expense'>('expense'); const [amount, setAmount] = useState(''); const [category, setCategory] = useState(''); const [accountId, setAccountId] = useState(''); const [frequency, setFrequency] = useState('monthly'); const [startDate, setStartDate] = useState(today()); const [subscription, setSubscription] = useState(false);
  const load = useCallback(async () => { if (!isOnline) { setItems(snapshot?.recurring ?? []); setLoading(false); return; } try { const result = await read<{ templates?: RecurringTemplate[] }>('listRecurring'); setItems(result.templates ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Jadwal gagal dimuat.'); } finally { setLoading(false); } }, [isOnline, read, snapshot?.recurring]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const save = async () => { try { await mutate('createRecurring', { name: name.trim(), type, amount: parseMoney(amount), category, accountId, frequency, startDate, nextDueDate: startDate, isSubscription: subscription, active: true }); setOpen(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Jadwal gagal disimpan.'); } };
  return <View style={{ gap: spacing.md }}><AppButton icon={Plus} fullWidth disabled={!isOnline} onPress={() => setOpen(true)}>Tambah transaksi rutin</AppButton>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : !items.length ? <EmptyState title="Belum ada transaksi rutin" message="Template tidak mengubah saldo sampai Anda menekan Catat ke ledger." /> : items.map((item) => <Card key={item.id} style={{ gap: spacing.sm }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }}><View style={{ flex: 1 }}><AppText variant="title">{item.name}</AppText><AppText variant="caption" muted>{item.frequency} · berikutnya {formatDate(item.nextDueDate)}</AppText></View><StatusPill label={item.active ? 'Aktif' : 'Pause'} tone={item.active ? 'positive' : 'neutral'} /></View><Amount value={item.type === 'expense' ? -item.amount : item.amount} signed variant="title" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }}><AppButton tone="secondary" icon={RefreshCw} disabled={!item.active} onPress={() => setConfirming(item)}>Catat ke ledger</AppButton><AppButton tone="ghost" icon={item.active ? Pause : Play} onPress={() => void mutate('updateRecurring', { id: item.id, active: !item.active }).then(load)}>{item.active ? 'Pause' : 'Aktifkan'}</AppButton></View></Card>)}
    <AppBottomSheet visible={open} title="Transaksi rutin baru" onClose={() => setOpen(false)} footer={<AppButton fullWidth loading={isMutating} onPress={() => void save()}>Simpan template</AppButton>}><FormField label="Nama" value={name} onChangeText={setName} /><SelectField label="Tipe" value={type} onChange={(value) => { setType(value as 'income' | 'expense'); if (value === 'income') setSubscription(false); }} options={[{ label: 'Pengeluaran', value: 'expense' }, { label: 'Pemasukan', value: 'income' }]} /><MoneyInput label="Nominal" value={amount} onChangeValue={setAmount} /><SelectField label="Kategori" value={category} onChange={setCategory} options={snapshot?.categories.filter((item) => item.active && item.type === type).map((item) => ({ label: item.name, value: item.name })) ?? []} /><SelectField label="Akun" value={accountId} onChange={setAccountId} options={snapshot?.accounts.map((item) => ({ label: item.name, value: item.id })) ?? []} /><SelectField label="Frekuensi" value={frequency} onChange={setFrequency} options={[{ label: 'Mingguan', value: 'weekly' }, { label: 'Bulanan', value: 'monthly' }, { label: 'Kuartalan', value: 'quarterly' }, { label: 'Tahunan', value: 'yearly' }]} /><DateField label="Tanggal mulai" value={startDate} onChange={setStartDate} />{type === 'expense' ? <SelectField label="Jenis" value={subscription ? 'subscription' : 'regular'} onChange={(value) => setSubscription(value === 'subscription')} options={[{ label: 'Transaksi rutin', value: 'regular' }, { label: 'Langganan', value: 'subscription' }]} /> : null}</AppBottomSheet>
    <ConfirmDialog visible={Boolean(confirming)} title="Catat ke ledger?" message={`${confirming?.name ?? ''} sebesar ${formatCurrency(confirming?.amount ?? 0)} akan dicatat pada ${formatDate(confirming?.nextDueDate ?? '')}, lalu jadwal berikutnya dimajukan secara atomik.`} confirmLabel="Catat" loading={isMutating} onCancel={() => setConfirming(null)} onConfirm={() => { if (!confirming) return; void mutate('confirmRecurring', { id: confirming.id, dueDate: confirming.nextDueDate }).then(() => { setConfirming(null); void load(); }).catch((cause) => { setConfirming(null); setError(cause instanceof Error ? cause.message : 'Gagal mencatat.'); }); }} />
  </View>;
}

export function ReviewModule() {
  const { snapshot, selectedMonth, read, mutate, isMutating, isOnline } = useApp();
  const [closing, setClosing] = useState<{ status: string; closedAt?: string | null } | null>(null); const [loading, setLoading] = useState(true); const [confirm, setConfirm] = useState<'close' | 'reopen' | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const result = await read<{ closing: { status: string; closedAt?: string | null } }>('monthlyClosingStatus', { period: selectedMonth }); setClosing(result.closing); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Status tutup buku gagal dimuat.'); } finally { setLoading(false); } }, [read, selectedMonth]);
  useEffect(() => { const timer = setTimeout(() => { if (isOnline) void load(); else setLoading(false); }, 0); return () => clearTimeout(timer); }, [isOnline, load]);
  const pending = snapshot?.transactions.filter((item) => item.status === 'pending' && item.date.startsWith(selectedMonth)).length ?? 0;
  if (loading) return <LoadingState />;
  return <View style={{ gap: spacing.md }}>{error ? <ErrorState message={error} onRetry={() => void load()} /> : null}<Card style={{ gap: spacing.sm }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><AppText variant="title">{formatMonth(selectedMonth)}</AppText><StatusPill label={closing?.status === 'closed' ? 'Ditutup' : 'Terbuka'} tone={closing?.status === 'closed' ? 'positive' : 'warning'} /></View><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><AppText muted>Pemasukan</AppText><Amount value={snapshot?.summary.income ?? 0} variant="label" /></View><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><AppText muted>Pengeluaran</AppText><Amount value={snapshot?.summary.expense ?? 0} variant="label" /></View><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><AppText muted>Transaksi pending</AppText><AppText variant="label">{pending}</AppText></View></Card><Card style={{ gap: spacing.xs }}><AppText variant="label">Checklist sebelum tutup buku</AppText>{['Semua transaksi sudah diperiksa', 'Saldo akun telah direkonsiliasi', 'Anggaran dan target sudah ditinjau', 'Tagihan periode ini sudah ditandai'].map((label) => <View key={label} style={{ flexDirection: 'row', gap: spacing.xs }}><CalendarCheck size={18} color="#126b59" /><AppText>{label}</AppText></View>)}</Card><AppButton fullWidth disabled={!isOnline || pending > 0} tone={closing?.status === 'closed' ? 'secondary' : 'primary'} onPress={() => setConfirm(closing?.status === 'closed' ? 'reopen' : 'close')}>{closing?.status === 'closed' ? 'Buka kembali periode' : 'Tutup buku periode ini'}</AppButton><ConfirmDialog visible={Boolean(confirm)} title={confirm === 'close' ? 'Tutup buku?' : 'Buka kembali periode?'} message={confirm === 'close' ? 'Mutasi ledger pada periode ini akan ditolak sampai periode dibuka kembali.' : 'Mutasi ledger pada periode ini akan diizinkan kembali dan dicatat di audit.'} confirmLabel={confirm === 'close' ? 'Tutup buku' : 'Buka kembali'} loading={isMutating} onCancel={() => setConfirm(null)} onConfirm={() => { const action = confirm === 'close' ? 'closeMonthlyBook' : 'reopenMonthlyBook'; const payload = confirm === 'close' ? { period: selectedMonth, confirmed: true, snapshot: { summary: snapshot?.summary, accountCount: snapshot?.accounts.length, budgetCount: snapshot?.budgets.length, goalCount: snapshot?.goals.length } } : { period: selectedMonth }; void mutate(action, payload).then(() => { setConfirm(null); void load(); }).catch((cause) => { setConfirm(null); setError(cause instanceof Error ? cause.message : 'Aksi tutup buku gagal.'); }); }} /></View>;
}
