function api(action, payload) {
  const routes = {
    setup: function() { return setupVinnStore(); },
    health: function() { return apiHealthCheck(); },
    bootstrap: function() { return apiGetBootstrap(payload && payload.month); },
    setupWorkspace: function() { return apiSetupWorkspace(payload || {}); },
    createAccount: function() { return apiCreateAccount(payload || {}); },
    archiveAccount: function() { return apiArchiveAccount(payload || {}); },
    createTransaction: function() { return apiCreateTransaction(payload || {}); },
    updateTransaction: function() { return apiUpdateTransaction(payload || {}); },
    listTransactions: function() { return apiListTransactions(payload || {}); },
    deleteTransaction: function() { return apiDeleteTransaction(payload.transactionId, payload.requestId, payload.expectedUpdatedAt); },
    importTransactions: function() { return apiImportTransactions(payload || {}); },
    undoTransaction: function() { return apiUndoTransaction(payload || {}); },
    attachTransactionReceipt: function() { return apiAttachTransactionReceipt(payload || {}); },
    deleteTransactionReceipt: function() { return apiDeleteTransactionReceipt(payload || {}); },
    reconcileAccount: function() { return apiReconcileAccount(payload || {}); },
    inspectLedger: function() { return apiInspectLedger(); },
    repairLedger: function() { return apiRepairLedger(payload || {}); },
    listCategories: function() { return apiListCategories(payload || {}); },
    createCategory: function() { return apiCreateCategory(payload || {}); },
    updateCategory: function() { return apiUpdateCategory(payload || {}); },
    archiveCategory: function() { return apiArchiveCategory(payload || {}); },
    listAuditLogs: function() { return apiListAuditLogs(payload || {}); },
    upsertBudget: function() { return apiUpsertBudget(payload || {}); },
    createGoal: function() { return apiCreateGoal(payload || {}); },
    contributeGoal: function() { return apiContributeGoal(payload || {}); },
    createBill: function() { return apiCreateBill(payload || {}); },
    markBillPaid: function() { return apiMarkBillPaid(payload || {}); },
    createInvestmentAsset: function() { return apiCreateInvestmentAsset(payload || {}); },
    updateInvestmentAsset: function() { return apiUpdateInvestmentAsset(payload || {}); },
    createInvestmentTrade: function() { return apiCreateInvestmentTrade(payload || {}); },
    backup: function() { return apiCreateBackup('manual'); },
    createBackup: function() { return apiCreateBackup('manual'); },
    backupOverview: function() { return apiBackupOverview(); },
    updateBackupSchedule: function() { return apiUpdateBackupSchedule(payload || {}); },
    listReports: function() { return apiListReports(); },
    saveReportPdf: function() { return apiSaveReportPdf(payload || {}); },
    migrationHistory: function() { return apiMigrationHistory(); },
    previewMigration: function() { return apiPreviewMigration(payload || {}); },
    applyMigration: function() { return apiApplyMigration(payload || {}); },
    cancelMigration: function() { return apiCancelMigration(payload || {}); },
    notificationOverview: function() { return apiNotificationOverview(payload || {}); },
    updateNotificationSettings: function() { return apiUpdateNotificationSettings(payload || {}); },
    updateNotificationState: function() { return apiUpdateNotificationState(payload || {}); },
    saveAiKey: function() { return apiSaveAiKey(payload.provider, payload.apiKey); },
    aiKeyStatus: function() { return apiAiKeyStatus(payload && payload.provider); },
    aiSettings: function() { return apiAiSettings(); },
    updateAiSettings: function() { return apiUpdateAiSettings(payload || {}); },
    aiHistory: function() { return apiAiHistory(); },
    askAi: function() { return apiAskAi(payload || {}); },
    clearAiHistory: function() { return apiClearAiHistory(); },
    ocrReceipt: function() { return apiOcrReceipt(payload || {}); }
  };
  try {
    if (!routes[action]) throw createError_('ROUTE_NOT_FOUND', 'Aksi API tidak dikenal: ' + action);
    return routes[action]();
  } catch (error) { return fail_(error, payload && payload.requestId); }
}
