function api(action, payload) {
  payload = payload || {};
  const publicActions = { health: true, whoami: true, memberLogin: true };
  let context = null;
  try {
    if (!publicActions[action]) context = resolveMemberContext_(payload.sessionToken);
    setRequestMemberContext_(context);
    if (context && context.mode === 'couple' && context.member.mustChangePin && action !== 'changeOwnPin') {
      throw createError_('PIN_CHANGE_REQUIRED', 'Ganti PIN sementara sebelum melanjutkan.');
    }
    const routes = {
      setup: function() { return setupFinancialPlanner(context); },
      health: function() { return apiHealthCheck(); },
      whoami: function() { return apiWhoami(payload); },
      memberLogin: function() { return apiMemberLogin(payload); },
      listMembers: function() { return apiListMembers(payload, context); },
      createMember: function() { return apiCreateMember(payload, context); },
      updateMember: function() { return apiUpdateMember(payload, context); },
      changeOwnPin: function() { return apiChangeOwnPin(payload, context); },
      mutationStatus: function() { return apiMutationStatus(payload, context); },
      bootstrap: function() { return apiGetBootstrap(payload && payload.month, context); },
      licenseStatus: function() { return apiLicenseStatus(context); },
      activateLicense: function() { return apiActivateLicense(payload, context); },
      deactivateLicense: function() { return apiDeactivateLicense(payload, context); },
      setupWorkspace: function() { return apiSetupWorkspace(payload, context); },
      upgradeWorkspace: function() { return setupFinancialPlanner(context); },
      updateProfile: function() { return apiUpdateProfile(payload, context); },
      updateFeaturePreferences: function() { return apiUpdateFeaturePreferences(payload, context); },
      getRoadmapSettings: function() { return apiRoadmapSettings(context); },
      updateRoadmapSettings: function() { return apiUpdateRoadmapSettings(payload, context); },
      getDebtPlanner: function() { return apiDebtPlanner(context); },
      updateDebtPlanner: function() { return apiUpdateDebtPlanner(payload, context); },
      getCashflowForecastSettings: function() { return apiCashflowForecastSettings(context); },
      updateCashflowForecastSettings: function() { return apiUpdateCashflowForecastSettings(payload, context); },
      getEmergencyFundSettings: function() { return apiEmergencyFundSettings(context); },
      updateEmergencyFundSettings: function() { return apiUpdateEmergencyFundSettings(payload, context); },
      monthlyClosingStatus: function() { return apiMonthlyClosingStatus(payload, context); },
      closeMonthlyBook: function() { return apiCloseMonthlyBook(payload, context); },
      reopenMonthlyBook: function() { return apiReopenMonthlyBook(payload, context); },
      createAccount: function() { return apiCreateAccount(payload, context); },
      createReceivable: function() { return apiCreateReceivable(payload, context); },
      updateAccount: function() { return apiUpdateAccount(payload, context); },
      importAccounts: function() { return apiImportAccounts(payload, context); },
      archiveAccount: function() { return apiArchiveAccount(payload, context); },
      createTransaction: function() { return apiCreateTransaction(payload, context); },
      recordLoanDrawdown: function() { return apiRecordLoanDrawdown(payload, context); },
      updateTransaction: function() { return apiUpdateTransaction(payload, context); },
      listTransactions: function() { return apiListTransactions(payload, context); },
      deleteTransaction: function() { return apiDeleteTransaction(payload.transactionId, payload.requestId, payload.expectedUpdatedAt, context); },
      importTransactions: function() { return apiImportTransactions(payload, context); },
      undoTransaction: function() { return apiUndoTransaction(payload, context); },
      attachTransactionReceipt: function() { return apiAttachTransactionReceipt(payload, context); },
      deleteTransactionReceipt: function() { return apiDeleteTransactionReceipt(payload, context); },
      reconcileAccount: function() { return apiReconcileAccount(payload, context); },
      inspectLedger: function() { return apiInspectLedger(context); },
      repairLedger: function() { return apiRepairLedger(payload, context); },
      listCategories: function() { return apiListCategories(payload, context); },
      createCategory: function() { return apiCreateCategory(payload, context); },
      updateCategory: function() { return apiUpdateCategory(payload, context); },
      archiveCategory: function() { return apiArchiveCategory(payload, context); },
      categoryRules: function() { return apiCategoryRules(context); },
      createCategoryRule: function() { return apiCreateCategoryRule(payload, context); },
      updateCategoryRule: function() { return apiUpdateCategoryRule(payload, context); },
      deleteCategoryRule: function() { return apiDeleteCategoryRule(payload, context); },
      listAuditLogs: function() { return apiListAuditLogs(payload, context); },
      upsertBudget: function() { return apiUpsertBudget(payload, context); },
      updateBudget: function() { return apiUpdateBudget(payload, context); },
      deleteBudget: function() { return apiDeleteBudget(payload, context); },
      createGoal: function() { return apiCreateGoal(payload, context); },
      updateGoal: function() { return apiUpdateGoal(payload, context); },
      deleteGoal: function() { return apiDeleteGoal(payload, context); },
      contributeGoal: function() { return apiContributeGoal(payload, context); },
      createSinkingFund: function() { return apiCreateSinkingFund(payload, context); },
      updateSinkingFund: function() { return apiUpdateSinkingFund(payload, context); },
      archiveSinkingFund: function() { return apiArchiveSinkingFund(payload, context); },
      adjustSinkingFund: function() { return apiAdjustSinkingFund(payload, context); },
      createBill: function() { return apiCreateBill(payload, context); },
      updateBill: function() { return apiUpdateBill(payload, context); },
      deleteBill: function() { return apiDeleteBill(payload, context); },
      markBillPaid: function() { return apiMarkBillPaid(payload, context); },
      listRecurring: function() { return apiListRecurring(context); },
      createRecurring: function() { return apiCreateRecurring(payload, context); },
      updateRecurring: function() { return apiUpdateRecurring(payload, context); },
      confirmRecurring: function() { return apiConfirmRecurring(payload, context); },
      createInvestmentAsset: function() { return apiCreateInvestmentAsset(payload, context); },
      updateInvestmentAsset: function() { return apiUpdateInvestmentAsset(payload, context); },
      createInvestmentTrade: function() { return apiCreateInvestmentTrade(payload, context); },
      backup: function() { return apiCreateBackup('manual', context); },
      createBackup: function() { return apiCreateBackup('manual', context); },
      backupOverview: function() { return apiBackupOverview(context); },
      updateBackupSchedule: function() { return apiUpdateBackupSchedule(payload, context); },
      listReports: function() { return apiListReports(context); },
      saveReportPdf: function() { return apiSaveReportPdf(payload, context); },
      migrationHistory: function() { return apiMigrationHistory(context); },
      previewMigration: function() { return apiPreviewMigration(payload, context); },
      applyMigration: function() { return apiApplyMigration(payload, context); },
      cancelMigration: function() { return apiCancelMigration(payload, context); },
      notificationOverview: function() { return apiNotificationOverview(payload, context); },
      updateNotificationSettings: function() { return apiUpdateNotificationSettings(payload, context); },
      updateNotificationState: function() { return apiUpdateNotificationState(payload, context); },
      saveAiKey: function() { return apiSaveAiKey(payload.provider, payload.apiKey, context); },
      aiKeyStatus: function() { return apiAiKeyStatus(payload && payload.provider, context); },
      aiSettings: function() { return apiAiSettings(context); },
      updateAiSettings: function() { return apiUpdateAiSettings(payload, context); },
      aiHistory: function() { return apiAiHistory(context); },
      askAi: function() { return apiAskAi(payload, context); },
      clearAiHistory: function() { return apiClearAiHistory(context); },
      ocrReceipt: function() { return apiOcrReceipt(payload, context); }
    };
    if (!routes[action]) throw createError_('ROUTE_NOT_FOUND', 'Aksi API tidak dikenal: ' + action);
    requireActionPlan_(action, payload);
    return routes[action]();
  } catch (error) {
    return fail_(error, payload && payload.requestId);
  } finally {
    setRequestMemberContext_(null);
  }
}
