function api(action, payload) {
  const routes = {
    setup: function() { return setupFinancialPlanner(); },
    health: function() { return apiHealthCheck(); },
    mutationStatus: function() { return apiMutationStatus(payload || {}); },
    bootstrap: function() { return apiGetBootstrap(payload && payload.month); },
    licenseStatus: function() { return apiLicenseStatus(); },
    activateLicense: function() { return apiActivateLicense(payload || {}); },
    deactivateLicense: function() { return apiDeactivateLicense(payload || {}); },
    setupWorkspace: function() { return apiSetupWorkspace(payload || {}); },
    updateProfile: function() { return apiUpdateProfile(payload || {}); },
    updateFeaturePreferences: function() { return apiUpdateFeaturePreferences(payload || {}); },
    getRoadmapSettings: function() { return apiRoadmapSettings(); },
    updateRoadmapSettings: function() { return apiUpdateRoadmapSettings(payload || {}); },
    getDebtPlanner: function() { return apiDebtPlanner(); },
    updateDebtPlanner: function() { return apiUpdateDebtPlanner(payload || {}); },
    getCashflowForecastSettings: function() { return apiCashflowForecastSettings(); },
    updateCashflowForecastSettings: function() { return apiUpdateCashflowForecastSettings(payload || {}); },
    getEmergencyFundSettings: function() { return apiEmergencyFundSettings(); },
    updateEmergencyFundSettings: function() { return apiUpdateEmergencyFundSettings(payload || {}); },
    monthlyClosingStatus: function() { return apiMonthlyClosingStatus(payload || {}); },
    closeMonthlyBook: function() { return apiCloseMonthlyBook(payload || {}); },
    reopenMonthlyBook: function() { return apiReopenMonthlyBook(payload || {}); },
    createAccount: function() { return apiCreateAccount(payload || {}); },
    updateAccount: function() { return apiUpdateAccount(payload || {}); },
    importAccounts: function() { return apiImportAccounts(payload || {}); },
    archiveAccount: function() { return apiArchiveAccount(payload || {}); },
    createTransaction: function() { return apiCreateTransaction(payload || {}); },
    recordLoanDrawdown: function() { return apiRecordLoanDrawdown(payload || {}); },
    updateTransaction: function() { return apiUpdateTransaction(payload || {}); },
    listTransactions: function() { return apiListTransactions(payload || {}); },
    deleteTransaction: function() { return apiDeleteTransaction(payload.transactionId, payload.requestId, payload.expectedUpdatedAt); },
    importTransactions: function() { return apiImportTransactions(payload || {}); },
    undoTransaction: function() { return apiUndoTransaction(payload || {}); },
    attachTransactionReceipt: function() { return apiAttachTransactionReceipt(payload || {}); },
    deleteTransactionReceipt: function() { return apiDeleteTransactionReceipt(payload || {}); },
    reconcileAccount: function() { return apiReconcileAccount(payload || {}); },
    inspectLedger: function() { return apiInspectLedger(); },
    repairLedger: function() { return apiRepairLedger(payload || {}); },
    listCategories: function() { return apiListCategories(payload || {}); },
    createCategory: function() { return apiCreateCategory(payload || {}); },
    updateCategory: function() { return apiUpdateCategory(payload || {}); },
    archiveCategory: function() { return apiArchiveCategory(payload || {}); },
    categoryRules: function() { return apiCategoryRules(); },
    createCategoryRule: function() { return apiCreateCategoryRule(payload || {}); },
    updateCategoryRule: function() { return apiUpdateCategoryRule(payload || {}); },
    deleteCategoryRule: function() { return apiDeleteCategoryRule(payload || {}); },
    listAuditLogs: function() { return apiListAuditLogs(payload || {}); },
    upsertBudget: function() { return apiUpsertBudget(payload || {}); },
    updateBudget: function() { return apiUpdateBudget(payload || {}); },
    deleteBudget: function() { return apiDeleteBudget(payload || {}); },
    createGoal: function() { return apiCreateGoal(payload || {}); },
    updateGoal: function() { return apiUpdateGoal(payload || {}); },
    deleteGoal: function() { return apiDeleteGoal(payload || {}); },
    contributeGoal: function() { return apiContributeGoal(payload || {}); },
    createSinkingFund: function() { return apiCreateSinkingFund(payload || {}); },
    updateSinkingFund: function() { return apiUpdateSinkingFund(payload || {}); },
    archiveSinkingFund: function() { return apiArchiveSinkingFund(payload || {}); },
    adjustSinkingFund: function() { return apiAdjustSinkingFund(payload || {}); },
    createBill: function() { return apiCreateBill(payload || {}); },
    updateBill: function() { return apiUpdateBill(payload || {}); },
    deleteBill: function() { return apiDeleteBill(payload || {}); },
    markBillPaid: function() { return apiMarkBillPaid(payload || {}); },
    listRecurring: function() { return apiListRecurring(); },
    createRecurring: function() { return apiCreateRecurring(payload || {}); },
    updateRecurring: function() { return apiUpdateRecurring(payload || {}); },
    confirmRecurring: function() { return apiConfirmRecurring(payload || {}); },
    createInvestmentAsset: function() { return apiCreateInvestmentAsset(payload || {}); },
    updateInvestmentAsset: function() { return apiUpdateInvestmentAsset(payload || {}); },
    createInvestmentTrade: function() { return apiCreateInvestmentTrade(payload || {}); },
    backup: function() { return apiCreateBackup('manual'); },
    createBackup: function() { return apiCreateBackup('manual'); },
    backupOverview: function() { return apiBackupOverview(); },
    updateBackupSchedule: function() { return apiUpdateBackupSchedule(payload || {}); },
    listReports: function() { return apiListReports(); },
    saveReportPdf: function() { return apiSaveReportPdf(payload || {}); },
    migrationHistory: function() { return apiMigrationHistory(); },
    previewMigration: function() { return apiPreviewMigration(payload || {}); },
    applyMigration: function() { return apiApplyMigration(payload || {}); },
    cancelMigration: function() { return apiCancelMigration(payload || {}); },
    notificationOverview: function() { return apiNotificationOverview(payload || {}); },
    updateNotificationSettings: function() { return apiUpdateNotificationSettings(payload || {}); },
    updateNotificationState: function() { return apiUpdateNotificationState(payload || {}); },
    saveAiKey: function() { return apiSaveAiKey(payload.provider, payload.apiKey); },
    aiKeyStatus: function() { return apiAiKeyStatus(payload && payload.provider); },
    aiSettings: function() { return apiAiSettings(); },
    updateAiSettings: function() { return apiUpdateAiSettings(payload || {}); },
    aiHistory: function() { return apiAiHistory(); },
    askAi: function() { return apiAskAi(payload || {}); },
    clearAiHistory: function() { return apiClearAiHistory(); },
    ocrReceipt: function() { return apiOcrReceipt(payload || {}); }
  };
  try {
    if (!routes[action]) throw createError_('ROUTE_NOT_FOUND', 'Aksi API tidak dikenal: ' + action);
    requireActionPlan_(action, payload || {});
    return routes[action]();
  } catch (error) { return fail_(error, payload && payload.requestId); }
}
